# Generated by Django 3.0 on 2020-11-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201103_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='has_coach',
            field=models.BooleanField(default=False),
        ),
    ]
